// <auto-generated />
namespace MiracleStone.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class farsi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(farsi));
        
        string IMigrationMetadata.Id
        {
            get { return "201410281452181_farsi"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
